### ISSUE TITLE
Request for referring original resource of Github repository

### ISSUE THREAD

**Issue by YeongHyeon** [ForrestPi/AnomalyDetection#1]
The 'png' files you used for the two links below were drawn separately by myself within the source code implementation.
https://github.com/ForrestPi/AnomalyDetection/tree/master/adVAE
https://github.com/ForrestPi/AnomalyDetection/tree/master/memae

If you don't mind, please refer to my GitHub repository for using the figures.
adVAE: https://github.com/YeongHyeon/adVAE
MemAE: https://github.com/YeongHyeon/MemAE or https://github.com/YeongHyeon/MemAE-TF2

**Comment by YeongHyeon** [comment]
I added a watermark to the picture that you used my figure in this repository. Considering this point, you should update the figure and insert the reference.

**Comment by ForrestPi** [comment]
So Sorry  I have changed . Sorry again
